/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface ViewDone {
    }
    interface ViewHome {
        "history": RouterHistory;
    }
    interface ViewIdentify {
    }
    interface ViewRecover {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLViewDoneElement extends Components.ViewDone, HTMLStencilElement {
    }
    var HTMLViewDoneElement: {
        prototype: HTMLViewDoneElement;
        new (): HTMLViewDoneElement;
    };
    interface HTMLViewHomeElement extends Components.ViewHome, HTMLStencilElement {
    }
    var HTMLViewHomeElement: {
        prototype: HTMLViewHomeElement;
        new (): HTMLViewHomeElement;
    };
    interface HTMLViewIdentifyElement extends Components.ViewIdentify, HTMLStencilElement {
    }
    var HTMLViewIdentifyElement: {
        prototype: HTMLViewIdentifyElement;
        new (): HTMLViewIdentifyElement;
    };
    interface HTMLViewRecoverElement extends Components.ViewRecover, HTMLStencilElement {
    }
    var HTMLViewRecoverElement: {
        prototype: HTMLViewRecoverElement;
        new (): HTMLViewRecoverElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "view-done": HTMLViewDoneElement;
        "view-home": HTMLViewHomeElement;
        "view-identify": HTMLViewIdentifyElement;
        "view-recover": HTMLViewRecoverElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ViewDone {
    }
    interface ViewHome {
        "history"?: RouterHistory;
    }
    interface ViewIdentify {
    }
    interface ViewRecover {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "view-done": ViewDone;
        "view-home": ViewHome;
        "view-identify": ViewIdentify;
        "view-recover": ViewRecover;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "view-done": LocalJSX.ViewDone & JSXBase.HTMLAttributes<HTMLViewDoneElement>;
            "view-home": LocalJSX.ViewHome & JSXBase.HTMLAttributes<HTMLViewHomeElement>;
            "view-identify": LocalJSX.ViewIdentify & JSXBase.HTMLAttributes<HTMLViewIdentifyElement>;
            "view-recover": LocalJSX.ViewRecover & JSXBase.HTMLAttributes<HTMLViewRecoverElement>;
        }
    }
}
